### ISSUE TITLE
在pypi里的rabird直接安装有问题

### ISSUE THREAD

**Issue by Dreamapple** [starofrainnight/rabird.winio#1]
安装会报错，没有rabird.core模块。
安装时有些依赖，没有解决貌似。

**Comment by starofrainnight** [comment]
Sorry for inconvenient, but you have to install pywin32 package which we depends on before you install our package.

There have no easy way to install pywin32 package just like pip or easy_install, you have to install it  manually first:

pywin32 : http://sourceforge.net/projects/pywin32/

I'm trying to find a way could solve this dependence problem, hope that won't take long time to go:
https://github.com/starofrainnight/rabird.core/issues/2

**Comment by starofrainnight** [comment]
This problem could be solved by rabird.core v0.3.0 : 

https://github.com/starofrainnight/rabird.core/releases/tag/v0.3.0
