### ISSUE TITLE
pywinio，可以实现鼠标模拟么，怎么实现，请指教

### ISSUE THREAD

**Issue by renyishou** [starofrainnight/rabird.winio#10]
pywinio，可以实现鼠标模拟么，怎么实现，就指教

**Comment by starofrainnight** [comment]
可以，pywinio 只是 winio 库的封装，winio 库可以实现的，它也能实现。至于如何实现，这个在国内外各大技术论坛上去问比较合适。这里的Issue列表仅用于讨论本库的缺陷，问题，修正或相关的建议，不负责教学。
