### ISSUE TITLE
how to use winio make mouse click

### ISSUE THREAD

**Issue by aa3222119** [starofrainnight/rabird.winio#11]
* pywinio version:0.2.6
* Python version:3.7
* Operating System:win64

### Description
keyboard模拟成功了，找了几个鼠标模拟的试了下，没效果；是我写的有问题还是目前还不支持，或者和我实际用的鼠标有关？

### What I Did
大致是这么写的用来驱动级触发left click

```
# Command port
KBC_KEY_CMD = 0x64
# Data port
KBC_KEY_DATA = 0x60
__winio = None


def __get_winio():
    global __winio

    if __winio is None:
            __winio = rabird.winio.WinIO()
            def __clear_winio():
                    global __winio
                    __winio = None
            atexit.register(__clear_winio)

    return __winio

winio = __get_winio()


def to_mouse_byte(byte_code=0x08):
    wait_for_buffer_empty()
    winio.set_port_dword(KBC_KEY_CMD, 0xd3)
    wait_for_buffer_empty()
    winio.set_port_dword(KBC_KEY_DATA, byte_code)
to_mouse_byte(0x09)
to_mouse_byte(0x00)
to_mouse_byte(0x00)
to_mouse_byte(0x00)
to_mouse_byte(0x08)
to_mouse_byte(0x00)
to_mouse_byte(0x00)
to_mouse_byte(0x00)


```
but it doesn't work

**Comment by starofrainnight** [comment]
This library just the API wrapper of WinIO, I give a sample about keyboard emulation just for showing the wrapper  works.  And WinIO is a library provied directly access I/O ports and physical memory. That's all.

I don't know the details about how the mouse works,  so if you want to emulate the mouse just find your way by yourself.

Tips: If you are testing on Win10 or later, you **MUST** have  a real ps/2 mouse connected (same as the situation of keyboard emulation - I guess).

**Comment by aa3222119** [comment]
感谢，我也刚发现了我的win10笔记本上没有PS/2鼠标，最近看到似乎HID的话就不存在走驱动模拟了，走HID/USB的话也许就需要能实际产生信号的设备(鼠标/ARM)了，再就是看看虚拟一个PS/2鼠标是否可行了。
![image](https://user-images.githubusercontent.com/17636366/57852247-40e66c80-7815-11e9-96e9-208427e26b5c.png)
