### ISSUE TITLE
i can not use pywinio

### ISSUE THREAD

**Issue by shownb** [starofrainnight/rabird.winio#12]
* pywinio version:lastest
* Python version:Python 3.7.4
* Operating System:win7 64 ultimate sp1

### Description
i installed pywinio like this:
```
pip install pywinio
```
and run cmd as admin like that
> bcdedit.exe /set TESTSIGNING ON

and installed the cert from winio64.sys too.

and reboot the computer.the run the python script in the README.md.
i expected it will be a 'A' to be typed.but it just like that:
```
c:\auto>python test.py

c:\auto>
```

and i dit something wrong,look forward to receiving your reply.

**Comment by shownb** [comment]
i try to installed the same thing in windows 7 32bit sp1
but both of them are in vmware env.
the same thing happened.
it must be have a real ps/2 keyboard?

**Comment by starofrainnight** [comment]
There have been declared in "Usage" section of README.md:

>  NOTICE: You must have a ps/2 keyboard connected to your PC if you test on win10 or later, otherwise this sample won't works!

Secondary, when you test in  in windows 7 32bit sp1, have you run it by "Run as Administrator" ?

See "Driver Signing Requirements on 64-bit Systems" section of README.md

**Comment by shownb** [comment]
all of them are running in vmware.so they don't have the real ps2 keyboard.

i think it is the problem about ps2 keyboard.because i can success in a old thinkpad.

maybe i need to consider like this article?
http://kinmeniotfirmwaresecurity.blogspot.com/2017/12/vmware-io-space-0x1015.html?m=1

and i tried to do this

windll.LoadLibrary("WinIo32.dll") when I invok the funcation InitializeWinIo(),it's always return 0

**Comment by starofrainnight** [comment]
Maybe the problem just like you said, I have not met the situation before.

windll.LoadLibrary("WinIo32.dll") won't works! WinIo*.sys path is hard-coded inside WinIo*.dll, so it won't load the driver correctly if you not placed the WinIO*.sys in the correct path. That's the reason  why I  write pywinio with pure python implementation as a replacement of WinIO*.dll in python.

**Comment by shownb** [comment]
so thank you.just close this issues.i will find another way.

**Comment by meetmez** [comment]
> so thank you.just close this issues.i will find another way.

did you find another way?
