### ISSUE TITLE
pywintypes.error: (3, 'StartService', 'The system cannot find the path specified.') when using pyinstaller

### ISSUE THREAD

**Issue by Raymon9** [starofrainnight/rabird.winio#13]
* pywinio version:0.3.1
* Python version:3.7
* Operating System:win10,64bit

### Description

An exception occur when i pack the py file to an exe file using pyinstaller.
But the py file run well before packed.

### What I Did

```
I packed the pywinio code as  keypress.py, and import it in the main.py, 'import keypress', the error throwed when i run the exe file:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "presser.py", line 257, in run
  File "keypress.py", line 53, in key_press
  File "keypress.py", line 37, in key_down
  File "keypress.py", line 17, in get_winio
  File "site-packages\pywinio\pywinio.py", line 133, in __init__
  File "site-packages\pywinio\pywinio.py", line 401, in __initialize
  File "site-packages\pywinio\pywinio.py", line 352, in __start_driver
pywintypes.error: (3, 'StartService', 'The system cannot find the path specified.')
```
Anyone can help me? thanks for advance.

**Comment by starofrainnight** [comment]
pywinio depends on the winio binaries that bring  by winiobinary package, so if you want to package up the script, you have to write your pyinstaller package script correctly collect the binaries from winiobinary to distribution.

**Comment by Raymon9** [comment]
@starofrainnight 
Thanks! I have added the winiobinary package, but the same problem is still. I checked the log infomation of pyinstaller, the pywinio module have imported sucessfully.
It is the set of the pyinstaller below:
`# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['presser.py', 'keypress.py'],
             pathex=['D:\\python\\presser\\dabao'],
             binaries=[('winiobinary', '.'), ('winiobinary-0.0.6-py3.7.egg-info', '.')],
             datas=[('icon.ico', '.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='Presser',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=['vcruntime140.dll'],
          runtime_tmpdir=None,
          console=True, icon='d:\\python\\presser\\icon.ico')
`

**Comment by starofrainnight** [comment]
I'm not familiar with pyinstaller, you could take deepper to the code and find what cause the problem and get your way to it.

**Comment by MorgenZhu** [comment]
1. Uninstall Python completely
2. Install Python to the specified directory，D:\python
3. D:\python，Add the path to the OS and user environment variable
4. pyinstaller -F -w  code.py

By following the steps above, I have solved the problem

**Comment by MorgenZhu** [comment]
This is pyinstaller issue, PyInstaller packages the library to exe without importing the Winiobinary folder.
So we need to specify the packaging folder.

1. pyinstaller -F -w -uac-admin hello.py
2. It will create a file called hello.spec, open it
3. modify Analysis->datas as follows :
`a = Analysis(['batteryview.py'],
             pathex=['F:\\python-code\\python-tool\\battery'],
             binaries=[],
             datas=[('D:\python\Lib\site-packages\winiobinary','winiobinary')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)`

4. pyinstaller -F -w -uac-admin hello.spec
5. That will solve the problem
