### ISSUE TITLE
上下左右不生效

### ISSUE THREAD

**Issue by v514020751** [starofrainnight/rabird.winio#14]
Left 对应是是 0x56 这个吗?为什么我用这个打印出来是 '/'  这个符号的?

**Comment by starofrainnight** [comment]
请参考 https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html 

键盘码值在不同的键盘环境下也有所不同, 根据操作系统和环境不同也不同.

这个库只保证你能调用RING0操作, 但要实现什么东西, 这个要靠你自己研究了.

**Comment by v514020751** [comment]
e0 4b (Grey Left) ,e0和4b之间有空格应该怎么写?
