### ISSUE TITLE
关于鼠标

### ISSUE THREAD

**Issue by captainww** [starofrainnight/rabird.winio#15]
* pywinio version: 0.3
* Python version: 3.7
* Operating System: win10

鸿哥你好，我查阅了很多关于winio的资料，目前卡在鼠标上面；

不知道哪里找到使用端口的完整流程；

也许您能给我些建议？

**Comment by starofrainnight** [comment]
你是要模拟鼠标吧? 这方面我没做过哦, 没办法给你什么建议. win10 之后, 建议还是自己写虚拟鼠标驱动吧, winio 的作者已经消失好久了, 网站都没续期了. 估计 winio 已经废弃了.

**Comment by captainww** [comment]
嗯嗯 好吧，谢谢你哈
