### ISSUE TITLE
OSError: exception: privileged instruction

### ISSUE THREAD

**Issue by JobsLius** [starofrainnight/rabird.winio#16]
作者您好，我在测试的时候有时候会报出这个异常，我应当怎样解决呢。
环境是 win7 x86
python3.6

**Comment by starofrainnight** [comment]
有运行在管理员权限下面吗? 参考README.rst "Privilege Requirements" 章节.

**Comment by JobsLius** [comment]
您好作者,我是在管理员权限下运行的,在某些特殊的情景下出现,在64位操作系统下,不会有此问题.

**Comment by JobsLius** [comment]
感谢您的回复
