### ISSUE TITLE
虚拟机中模拟键盘没有反应且无异常输出

### ISSUE THREAD

**Issue by meetmez** [starofrainnight/rabird.winio#18]
* pywinio version:0.2.6
* Python version:2.7.12
* Operating System:winserver 2008 R2

### Description
作者您好：
       我在PC机和笔记本下已经测试ok 但是在虚拟机winserver2008R2中，以同样的方法，安装测试，没有反应，也没有异常输出

### What I Did
我这边前期的主要操作是：
   1. 安装证书
   2. 开启测试模式
   3. 用管理员启动cmd进行测试

```
我这边不知道后续怎么调试和处理，看看是因为虚拟机的问题还是PS2键盘属性的问题，我没办法确认和调试。
```

**Comment by starofrainnight** [comment]
不好意思, 我这边没有相关的环境, 没法测试. 一般情况下, 如果权限没有问题的话(注意!千万不要有360之类的安全软件,这些软件会禁止Ring0相关权限的操作), 就要检查机器有没有PS/2键盘(如果你是模拟PS/2键盘指令的话). 本项目仅是 winio 的 python 封装, 至于如何实现相关的操作或存在什么问题, 这个具体看你对 winio 的熟悉程度, 自己自行调试了.

**Comment by cielwp** [comment]
> * pywinio version:0.2.6
> * Python version:2.7.12
> * Operating System:winserver 2008 R2
> 
> ### Description
> 作者您好：
> 我在PC机和笔记本下已经测试ok 但是在虚拟机winserver2008R2中，以同样的方法，安装测试，没有反应，也没有异常输出
> 
> ### What I Did
> 我这边前期的主要操作是：
> 
> 1. 安装证书
> 2. 开启测试模式
> 3. 用管理员启动cmd进行测试
> 
> ```
> 我这边不知道后续怎么调试和处理，看看是因为虚拟机的问题还是PS2键盘属性的问题，我没办法确认和调试。
> ```

我也有同样的问题，我们相关的程序在win7上已经配置和运行的很成熟，但同样的配置在windows server 2008 R2 Enterprise 上就不起作用。

**Comment by cielwp** [comment]
> 不好意思, 我这边没有相关的环境, 没法测试. 一般情况下, 如果权限没有问题的话(注意!千万不要有360之类的安全软件,这些软件会禁止Ring0相关权限的操作), 就要检查机器有没有PS/2键盘(如果你是模拟PS/2键盘指令的话). 本项目仅是 winio 的 python 封装, 至于如何实现相关的操作或存在什么问题, 这个具体看你对 winio 的熟悉程度, 自己自行调试了.

在设备管理器-键盘中是有PS/2 标准键盘的。

**Comment by starofrainnight** [comment]
> > 不好意思, 我这边没有相关的环境, 没法测试. 一般情况下, 如果权限没有问题的话(注意!千万不要有360之类的安全软件,这些软件会禁止Ring0相关权限的操作), 就要检查机器有没有PS/2键盘(如果你是模拟PS/2键盘指令的话). 本项目仅是 winio 的 python 封装, 至于如何实现相关的操作或存在什么问题, 这个具体看你对 winio 的熟悉程度, 自己自行调试了.
> 
> 在设备管理器-键盘中是有PS/2 标准键盘的。

如果存在PS/2标准键盘, 那么问题估计是存在权限之类的吧, 还有一种可能就是 winio 在 windows server 系统上存在兼容性问题之类的, 这个需要您自己调试或者自己修改 winio 的驱动代码了.
