### ISSUE TITLE
can u solve my error?

### ISSUE THREAD

**Issue by respark** [starofrainnight/rabird.winio#6]
i use u sample then error:
Traceback (most recent call last):
  File "C:\py\rrd.py", line 2267, in <module>
    key_press(0x1E)
  File "C:\py\rrd.py", line 2229, in key_press
    key_down( scancode )
  File "C:\py\rrd.py", line 2215, in key_down
    wait_for_buffer_empty();
  File "C:\py\rrd.py", line 2210, in wait_for_buffer_empty
    dwRegVal = winio.get_port_byte(KBC_KEY_CMD)
  File "C:\Python27\lib\site-packages\rabird\winio.py", line 148, in get_port_byte
    return self.__get_port_value(wPortAddr, 1)
  File "C:\Python27\lib\site-packages\rabird\winio.py", line 138, in __get_port_value
    4))[0];
TypeError: expected a readable buffer object

**Comment by respark** [comment]
i install rabird.winio from pip

**Comment by respark** [comment]
version 0.1.11

**Comment by respark** [comment]
at last i test ok in win32,error in win64

**Comment by starofrainnight** [comment]
What os you are using? WinXP? Win7 ? Win8 or Win10?

**Comment by starofrainnight** [comment]
WinIO library is known that can't work with normal 64bits system until you solved driver signing problems : 

First read about this section in README.rst : "Driver Signing Requirements on 64-bit Systems“

**Comment by respark** [comment]
i use win10_x64 , i also set bcdedit.exe /set TESTSIGNING ON

**Comment by respark** [comment]
and import keys in system

**Comment by starofrainnight** [comment]
Yep, I tested on win10 x64 with python3, it could success executed but without any print out. I don't know why yet.

**Comment by starofrainnight** [comment]
I found the reason, please check #7
