### ISSUE TITLE
pip install pywinio failure.

### ISSUE THREAD

**Issue by TongAriel** [starofrainnight/rabird.winio#9]
* pywinio version: 0.3.0
* Python version: 2.7.15
* Operating System: Microsoft Windows [版本 10.0.17134.137] 64
pip version 18.0

### Description
pip install pywinio show error message as below.
Collecting pywinio
Using cached https://files.pythonhosted.org/packages/21/49/4e86ad4ec72018a5608a06802edd6d7282440654763395fcc1d4256ab0f0/pywinio-0.3.0.zip
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in 
File "c:\users\xxx\appdata\local\temp\pip-install-hw_v4n\pywinio\setup.py", line 8, in 
with open('README.rst', encoding='utf-8') as readme_file, 
TypeError: 'encoding' is an invalid keyword argument for this function

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\xxx\appdata\local\temp\pip-install-hw_v4n\pywinio\

### What I Did
Install pywinio failure.

:\>pip install pywinio

**Comment by starofrainnight** [comment]
pywinio (rabird.winio) library has dropped python 2.x support after 0.2.4.

So if you want to support python 2.x, you must install rabird.winio 0.2.4 specificly:

pip install rabird.winio==0.2.4

**Comment by starofrainnight** [comment]
No response, closed.
